### ISSUE TITLE
[文章][2022-04-22] 探索 Rust 中异步取消的未来

### ISSUE THREAD

**Issue by trdthg** [sunface/codecc#119]
原文标题: Perspectives on Async Cancellation

原文链接: https://blog.theincredibleholk.org/blog/2022/03/25/perspectives-on-async-cancellation/

译文链接: 

---
**选题者须知**

1. 修改 issue 标题：将 `类型` 修改为为 *文章*、*系列*、*书籍* 中的一个，并将 `日期` 和 `标题` 进行替换
2. 将上面的原文标题、原文链接和下面声明模版中的 `原文链接`、`选题` 替换成相应的内容

**翻译者须知**

1. 在issue中评论：申请翻译，并附上预期完成时间，等待一个 approver 来处理
2. 请翻译者在翻译后，将声明模版的 Markdown 文本加入到文章的 **顶部**

---
**声明模版**

```
> *本文选自 [Rust 翻译计划](https://rustt.org)，由 [RustCn](https://hirust.cn) 荣誉推出*
> 
> **翻译：_该部分由 Approver 替换填写_**
> 选题：[trdthg](https://github.com/trdthg)
>
> 原文链接: https://www.rust-lang.org
```

**Comment by sunface** [comment]
这个题目的中文翻译感觉没啥吸引力🤣

**Comment by trdthg** [comment]
那就润 💥

**Comment by sunface** [comment]
新的好多了，哈哈。
