### ISSUE TITLE
[文章][2022-04-08] 虚弱之塔：每个人都应该懂的内存模型

### ISSUE THREAD

**Issue by hyuuko1** [sunface/codecc#98]
原文标题: The Tower of Weakenings: Memory Models For Everyone

原文链接: https://gankra.github.io/blah/tower-of-weakenings/

**翻译者须知**

1. 在issue中评论：申请翻译，并附上预期完成时间，等待一个 approver 来处理
2. 请翻译者在翻译后，将声明模版的 Markdown 文本加入到文章的 **顶部**

**声明模版**

```
---
> 原文链接: https://gankra.github.io/blah/tower-of-weakenings/
> 
> **翻译：[Sunface](https://github.com/sunface)**
>
> 选题：[BK0717](https://github.com/hyuuko)
>
> 本文由 [Rustt](https://Rustt.org) 翻译，[StudyRust](https://studyrust.org) 荣誉推出
```

**Comment by sunface** [comment]
@sunface 申请翻译，预计完成 2022-04-13

**Comment by sunface** [comment]
`@rubot`

选题 + 8
